experiments/hello-git.txt

This file should be deleted after the pull request is done, since it has no other purpose.

adds a test file for the git mission

---

backend/auth.js
backend/azureiot.js
backend/browser-ws.js
backend/device-ws.js
backend/express.js
backend/index.js
backend/shuttle-control.js
backend/shuttle-telemetry.js
package-lock.json
package.json

I have created a proposal for an internal structure and API for the shuttle part of the back end. 
The video part will share some components like at least AzureIoT and Browser Web Sockets. But need to understand the code requirements better before I include that into the design.
There are some very important glue code that is missing. But we should be able to very easy create many small tasks based on this structure. And the Web Socket handling in express should be on the top of that list.

Proposal for internal API for shuttle part of the back end.

---

.env-default
backend/azureiot.js
backend/config.js
backend/config.test.js
backend/index.js
package-lock.json
package.json

Refactored the config code while I added config settings for device authentication.
Also had to fix up azureiot a bit to get the code to run.

Refactor config for device auth.

---

backend/index.js
backend/rtc-control.js
backend/video-stream.js
public/index.html
public/index.js
public/rtcConnector.js
public/videoView.js
public/websocket.js

Yea I have no idea what I am doing with this. RTC is very complicates for a person not the the know.

First try on a structure for video part of EIT Hub

---

backend/browser-ws.js

Adds a broadcast function to browser-ws.js that sends a json object to all available browsers

Add broadcast

---

package-lock.json
public/input.js

Gives the client a smoother control with keyboard as the values gradually increase/decrease between -1 and 1.

Add upgraded keyboard inputs

---

backend/shuttle-control.js
backend/shuttle-telemetry.js

ShuttleControl listens exclusively on messages with 'input' as topic/type. This should be enough for an end-to-end test.

Implement ShuttleControl and ShuttleTelemetry

---

devices/Shuttle/shuttle/config.py
devices/Shuttle/shuttle/shuttle_connector.py
devices/Shuttle/shuttle/shuttle_controller.py
devices/Shuttle/shuttle/websocket_connector.py

Changes a bit of the websocket_connector architecture to enable sending and recieving messages over the same websocket. Ideas for how to improve the readability or structure are very welcome

Device telemetry

---

backend/device-ws.js

'callback' needs to be defined in the for loop that executes all callbacks in _deviceCallback.

Add 'let' keyword to callback

---

backend/device-ws.js
backend/shuttle-telemetry.js
public/index.html
public/style.css
public/telemetryView.js
public/websocket.js

Simple telemetry can now be shown in browser. Also did small stuff to css file for browser. Some changes to html file, removed unused elements.

Add telemetry

---

Dockerfile
docker-compose.yml

And a docker compose for convenience.
This is the first part of hosting.
If you have docker installed you can now run the back end inside docker by running docker-compose up.

Written a dockerfile for eithub.

---

backend/auth.js
backend/auth.test.js
backend/auth/device-auth.js
backend/auth/device-auth.test.js
package-lock.json
package.json

I have written the code that generate and validates keys for devices.
What is left for device-auth is to integrate it with express and that is going to be fun.

Devicekey generation

---

public/clientRequests.js
public/index.html
public/index.js
public/websocket.js

The request control button send a sendControlReqeust to the websocket on client side with type inputControl. Answer should be as true/false with same message type

Add request control frontend

---

backend/azureiot.js
backend/config.js
backend/index.js
package-lock.json
package.json

onMessage in the AzureIot class now listens for messages to the IoT Hub from a selected device.

Implement IoT Hub message listener

---

backend/auth.js
backend/express.js
backend/tests/device-auth.test.js

We finally have device authentication.
I am personally very happy with the test file. Not only was useful while developing now its validates some parts of the back end. And its minimal demo of how to implement device authentication.

Device auth express

---

docs/design/readme.md

A very top level overview of the system I want to create.
Based on prototype the students are building. Some of internal API have been fundamental to the thinking of MVP.
Also the stuff i do not want to do any more .

EIT-Hub MVP design over veiw.

---

backend/shuttle-control.js

the localhost://3000 page are currently not responding with changing the “You are not in control / You are in control”. 
All the websites can still control the fake shuttle without having to push the request button.
When another more recent browser request control, previous browsers cannot re-request control or control the shuttle anymore without reloading the page.

browser control - a start

---

backend/browser-ws.js
backend/device-ws.js
backend/shuttle-control.js
public/clientRequests.js
public/index.html

A client may only gain control over the shuttle when no one else is controlling it. Trying to gain control or give up control is answered with a feedback message from the server. When the browser with control disconnects or gives up control, control is up for grabs once again.

Improved shuttle input control

---

backend/browser-ws.js
backend/shuttle-control.js
public/clientRequests.js

The frontend now shows which user is in control of the shuttle, instead of showing the browser ID.

Show user in control of shuttle

---

public/websocket.js

Client tried to connect to the localhost:3000 back end with web-socket this is a quick fix.

Relative url based on host-name

---

public/clientRequests.js
public/index.html
public/input.js
public/keyboard.js

Can change flight mode by pressing keys on keyboards. Press 1 for manual, 2 for stabilize and 3 for depth hold.

Add flightmode keyboard keys

---

docs/design/communication.md
docs/design/dashboards.md
docs/design/devices.md
docs/design/gui.md
docs/design/readme.md
docs/design/security.md
docs/design/services.md
docs/design/widget.md

Design MVP
